export default {
    TOKEN: 'whajjOOks%%--s',
    STORAGE_TOKEN: 'kay&sqq_storage',
  
  
    NETWORK_CHAINID: '0x38',
    ACCOUNT_BALANCE: 'ACCOUNT_BALANCE',
  
    ADDRESS: 'ADDRESS',
    CONNDETAILS: 'CONN_DETAILS',
    APYS: "ALL_APYS",
    NATIVE_BALANCE: 'NATIVE_BALANCE',
  
    PRISTINE: 'ALL_PRISTINE',

    PROTOCOLS: 'ALL_STABLECOIN_OFFERINGS',
    LENDER: 'LENDER_PROTOCOLS',
    //providerSet
    WEB3SETPROVIDER: 'WEB3_SET_PROVIDER',

    NETWORK_CONNECT:'NETWORK_CONNECT',
    CONWALLETADD:'WALLETCONN',

    USDTBALANCE:'USDT BALANCE',
    BUSDBALANCE:'BUSD BALANCE',
    USDCBALANCE:'USDC BALANCE',

    //providerSet
    WCP: 'WCProvider',
  
    //web3HasDisconnected
    WEB3_WALLETCONNECT_HAS_DISCONNECTED: 'WEB3_WALLETCONNECT_DISCONNECTED',
  
    //NewNetworkChange
    NETWORK_PROVIDER_HAS_CHANGED: 'SELECTED_NETWORK_PROVIDER',
    
    STORED_APYS: "__stored_apy__",
    APY_NOTICE: "APY_NOTICE",
  };
  