name: Layer2 UI
on:
  push:
    branches: [main]
jobs:
  layer2_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: echo "${{ secrets.GCP_VM_PRIVATE_KEY }}" > id_rsa
      - run: chmod -R 600 id_rsa
      - run: npm install && npm run build
      - run: scp -i id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r build/* franklin@35.225.70.160:/var/www/layer